### PR TITLE
DM-36264: Initial Rubin theming stylesheet for CILogon

### PR DESCRIPTION
**Pull request by jonathansick**
This is a first pass at creating a stylesheet for theming the CILogon page. The development environment consists of downloaded versions of the CILogon assets, along with the `rubin.css` file. It's only this `rubin.css` file that we'll need to pass along to CILogon.

The imagotype is an embedded SVG.

### CODE REVIEW

**Comment by jonathansick** [comment]
I haven't tried adding dark mode yet, but I'll give it a shot.

CleanShot 2022-09-21 at 18 37 23

**Comment by jonathansick** [comment]
I've added a dark mode; the only thing that isn't "dark" yet is the select menu and it's search UI.

CleanShot 2022-09-22 at 11 35 39

**Review by rra — APPROVED** [review]
Looks great to me. Thanks for including the screenshots!

It's not clear to me if we send them an overlay on top of cilogon.css or if we send them a full replacement for cilogon.css, FYI. I'll find out and let you know.

**Comment by jonathansick** [comment]
I'm pretty sure that what CILogon needs is just the `rubin.css` because they'll embed it in a `<style>` tag in the `<head>` of the HTML; they load `cilogon.css` separately via a `<link rel="stylesheet">`.

**Comment by jonathansick** [comment]
@rra I've updated `rubin.css` to fix the issues:

- Ensure the CILogon logo is visible
- Fix visited links in the footer
- Reset margin and padding on buttons for compatibility with the `/me` page
- Add theming for tables, like those found on the `/me` page.

**Comment by jonathansick** [comment]
Looks like the CSS has been accepted, so we'll merge this PR.

**Pull request merged**
